name: Format Lua code with StyLua

on:
  pull_request:
    paths:
      - "src/**/*.luau"
      - "stylua.toml"
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install StyLua
        run: cargo install stylua
      - name: Run StyLua
        run: stylua src
