name: Run TestEZ tests

on:
  pull_request:
    paths:
      - "src/**/*.luau"
      - "testEZ.yml"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.1'
      - name: Install Luarocks
        run: sudo apt-get update && sudo apt-get install -y luarocks
      - name: Install TestEZ
        run: luarocks install testez
      - name: Run TestEZ
        run: testez src/shared
